language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t wari0/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true wari0/docker-react npm run test
